language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

# command to install dependencies
#install:
#  - pip install tox
# command to run tests
script:
  - python setup.py sdist bdist_wheel
notifications:
  email:
    recipients:
      - somenzz@163.com
    on_success: change
    on_failure: always